### ISSUE TITLE
problem  while using custom  dataset

### ISSUE THREAD

**Issue by suman560** [MECLabTUDA/Super_Selfish#2]
stack expects each tensor to be equal size, but got [1, 225, 255] at entry 0 and [3, 225, 255] at entry 3

**Comment by nwWag** [comment]
Could you please provide some more information:
1. Are you using grayscale images ?
2. Best would be to state the full trace.

Thanks !

**Comment by suman560** [comment]
<img width="277" alt="3" src="https://user-images.githubusercontent.com/55105259/111632937-f3cbeb00-882f-11eb-8430-38bf31f3480c.png">
<img width="640" alt="4" src="https://user-images.githubusercontent.com/55105259/111632957-f9c1cc00-882f-11eb-8c05-fac5c81637e1.png">
Thank you for your response!

**Comment by nwWag** [comment]
This does not seem to be a Super-Selfish error. BYOL makes sure that gray augmentation still leads to 3 channels (see line 535 of data.py). The (pytorch) error is happening as you try to collate gray and rgb images. I could not reproduce your error. Perhaps, the img.convert('RGB') sometimes fails?
